### ISSUE TITLE
lost password -- any options?

### ISSUE THREAD

**Issue by bubfranks** [bither/bither-android#15]
I made a private key for a new faucet, not expecting to get paid, but then they did pay and now I don't remember the password. Not a big deal because it's a tiny amount, but now I want to try using HDM, and I have to know the password for that too.

I could uninstall and re-install, but I hate to delete private keys. Before I wipe the wallet I thought I would check here to see if there were any options for me.

I probably just mashed on the keyboard for the password. Otherwise I think I would have wrote it down. EDIT: but maybe not if I had to enter the password twice, yikes. EDIT: gah, nevermind. I just remembered it. <rolls eyes>

**Comment by songchenwen** [comment]
We are glad that you remembered your password. 

Bither won't store your password anywhere. 

If we store your password, we will be able to spend your money, which is definitely not the way you should use your bitcoins.

So you have to remember your password all by yourself. You can use the `check private key` function periodically to help you remember the password.

**Comment by bubfranks** [comment]
Hi, and thank you for your quick response. I used HDM successfully last night, and I have some feedback. First of all, I really enjoyed your product. Excellent work! Some thoughts during setup:

* The visual cues were very easy to understand, and the whirly action at the end made me happy. One of those messages during setup of "HDM-Server" was a little confusing. I forget which message it was, but maybe you could take a look at them. I'm thinking of the messages in the blue rectangles at the bottom of the interface. I wasn't immediately certain which barcode to scan.

* Also, what information does HDM-Server keep on its users?

Some thoughts during usage include:

* I see in the advanced options there is a way to view trashed addresses, but I don't see how to trash one of my addresses within HDM-Hot wallet. I like to use a new addresses for the change of each transaction, so the old addresses clutter up the interface a bit.

* I would like to be able to change the default signing pairs to use HDM-Cold rather than having to select it every time I send coin from HDM-Hot. The default is to sign with HDM-Server. Maybe this could be an advanced option. For me, having HDM-Server in the 2-of-3 scheme is reassuring, but it's not clear why I would need to use HDM-Server on a regular basis.

* Also, I would like to be able to change the default behavior related to change addresses. In order to make it easier to avoid address reuse, I would appreciate a way to change the default change address to "new HDM-Hot address." Currently the default is to send change back to the same address, which reduces privacy.

Lastly, I would appreciate any links to additional documentation on how HDM Bither works: 

* Does HDM-Cold cycle through multiple addresses or is it always signing with HDM-Cold[0]? What about HDM-Server? 

* Also, how to restore under various combinations of lost seeds and lost phones?

Many thanks for your attention.

**Comment by songchenwen** [comment]
Big thanks for your advice.

There's [a video on youtube](http://youtu.be/wHdKrwuom1Y) that demonstrates the HDM feature of Bither.

Regarding to your questions:

- HDM Server stores one of the three HD seeds of HDM and the authentication info of the user. The authentication is done by HDM Cold[0] via BitID.

- HDM Hot addresses currently can't be moved to trash can. Since we think that address's position in list indicating their indices in HDM account is straight forward. But we're still considering adding this function sometime.

- You may already know Bither has Cold/Hot modes. Bither Cold is meant to be placed in a secure place and rarely used. Bither Hot is meant to be the daily using phone. Cold addresses need to scan Bither Cold to send transactions, while Hot addresses send transactions all by itself. Therefore, Cold is for safety and Hot is for convenience. And we brought HDM in to balance the safety and convenience. HDM signs with the hot and the server by default, so you can take your Bither Hot phone around and use you bitcoins. But when you accidentally lose your Hot phone, you can come back home, pick up your Cold phone and restore your account to transfer your bitcoins to somewhere safe. This is why we keep Hot & Server the default signing parts. Also the advance default signing parts option you mentioned is still in our consideration.

- The default change behavior you mentioned will be on the way. We just need to consider how to make it fit in with our current app structure.

- HDM Server and Cold don't use one private key all the time. `HDM[n]` comes from `Hot[n]` + `Cold[n]` + `Server[n]`.

- When HDM server is down, you can use the `sign with cold` to spend your bitcoins. When Cold phone lost, use `sign with server`. When Hot phone lost, grab a new phone and use `advance - HDM recovery` to recover from Cold and Server.
